"""candidate selectionssa

Revision ID: 020aca631ea7
Revises: c4b737b62abe
Create Date: 2025-11-06 18:55:27.227901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020aca631ea7'
down_revision: Union[str, Sequence[str], None] = 'c4b737b62abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('selected_for_interview', sa.Boolean(), nullable=True))
    op.add_column('candidate', sa.Column('selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'selected')
    op.drop_column('candidate', 'selected_for_interview')
    # ### end Alembic commands ###
