"""update can table col meet link

Revision ID: 17365a1e8752
Revises: c218412dfa8c
Create Date: 2025-11-21 19:10:41.781148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17365a1e8752'
down_revision: Union[str, Sequence[str], None] = 'c218412dfa8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('meet_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'meet_link')
    # ### end Alembic commands ###
