"""add hr availability and interviews upthisagain 

Revision ID: 175d9a042627
Revises: 5fbe114d4335
Create Date: 2025-11-06 17:42:49.684771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175d9a042627'
down_revision: Union[str, Sequence[str], None] = '5fbe114d4335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
