"""add company col in job

Revision ID: 273edea2045b
Revises: 39d77636e1de
Create Date: 2025-11-17 06:28:07.040848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273edea2045b'
down_revision: Union[str, Sequence[str], None] = '39d77636e1de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'company_id')
    # ### end Alembic commands ###
