"""new department name

Revision ID: 34a0cb58d6e8
Revises: 1f093e364272
Create Date: 2025-11-15 19:46:27.908711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a0cb58d6e8'
down_revision: Union[str, Sequence[str], None] = '1f093e364272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('department_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'department_name')
    # ### end Alembic commands ###
