"""update createdat  col in job

Revision ID: 36f4b90bba76
Revises: d0dd7782b8bc
Create Date: 2025-11-18 19:11:46.073669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f4b90bba76'
down_revision: Union[str, Sequence[str], None] = 'd0dd7782b8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'created_at')
    # ### end Alembic commands ###
