"""add select availabilty

Revision ID: 39d77636e1de
Revises: 34a0cb58d6e8
Create Date: 2025-11-16 15:06:36.239680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d77636e1de'
down_revision: Union[str, Sequence[str], None] = '34a0cb58d6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_availability', sa.Column('is_selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_availability', 'is_selected')
    # ### end Alembic commands ###
