"""Add slug column to jobs

Revision ID: 3b6b6f345d1b
Revises: 3ef7a0260d8a
Create Date: 2025-09-20 11:08:29.597646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6b6f345d1b'
down_revision: Union[str, Sequence[str], None] = '3ef7a0260d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'job', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='unique')
    op.drop_column('job', 'slug')
    # ### end Alembic commands ###
