"""Add slug column to job

Revision ID: 3ef7a0260d8a
Revises: d453fdd5e90b
Create Date: 2025-09-20 10:57:10.238338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef7a0260d8a'
down_revision: Union[str, Sequence[str], None] = 'd453fdd5e90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'job', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='unique')
    op.drop_column('job', 'slug')
    # ### end Alembic commands ###
