"""refactor candidate table

Revision ID: 50bf6532f293
Revises: 18ace6cd9a17
Create Date: 2025-09-22 19:23:08.968981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50bf6532f293'
down_revision: Union[str, Sequence[str], None] = '18ace6cd9a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('candidate_email_key'), 'candidate', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('candidate_email_key'), 'candidate', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
