"""update can table add col company_id

Revision ID: 5fa64a855e2a
Revises: 17365a1e8752
Create Date: 2025-11-26 19:32:08.262196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa64a855e2a'
down_revision: Union[str, Sequence[str], None] = '17365a1e8752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'candidate', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'company_id')
    # ### end Alembic commands ###
