"""add hr availability and interviews upthis 

Revision ID: 5fbe114d4335
Revises: d53ab6d678d3
Create Date: 2025-11-06 17:16:23.605076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbe114d4335'
down_revision: Union[str, Sequence[str], None] = 'd53ab6d678d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['hr_availability.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.interview_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_slot_id'), 'interview_slot', ['id'], unique=False)
    op.add_column('interview', sa.Column('slot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interview', 'interview_slot', ['slot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_column('interview', 'slot_id')
    op.drop_index(op.f('ix_interview_slot_id'), table_name='interview_slot')
    op.drop_table('interview_slot')
    # ### end Alembic commands ###
