"""linkedin token

Revision ID: 6069f05c0e5c
Revises: fc65e793222d
Create Date: 2025-09-26 16:29:31.830473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6069f05c0e5c'
down_revision: Union[str, Sequence[str], None] = 'fc65e793222d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('urn', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hr_id'], ['hr_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_token_id'), 'linkedin_token', ['id'], unique=False)
    op.create_index(op.f('ix_linkedin_token_user_id'), 'linkedin_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_token_user_id'), table_name='linkedin_token')
    op.drop_index(op.f('ix_linkedin_token_id'), table_name='linkedin_token')
    op.drop_table('linkedin_token')
    # ### end Alembic commands ###
