"""candidate with null resume

Revision ID: 65019afbad81
Revises: 663c395e1590
Create Date: 2026-01-28 19:47:55.713010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65019afbad81'
down_revision: Union[str, Sequence[str], None] = '663c395e1590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'resume_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'resume_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
