"""refactored payment table

Revision ID: 66ccd673361c
Revises: f0e4d7d380a6
Create Date: 2025-09-22 18:47:28.571485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ccd673361c'
down_revision: Union[str, Sequence[str], None] = 'f0e4d7d380a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.add_column('payment', sa.Column('job_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('payment_application_id_fkey'), 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'candidate', ['candidate_id'], ['candidate_id'])
    op.create_foreign_key(None, 'payment', 'job', ['job_id'], ['job_id'])
    op.drop_column('payment', 'application_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key(op.f('payment_application_id_fkey'), 'payment', 'application', ['application_id'], ['application_id'])
    op.drop_column('payment', 'job_id')
    op.drop_column('payment', 'candidate_id')
    # ### end Alembic commands ###
