"""removed company name uniqueness

Revision ID: 70e2033a14a9
Revises: a28fa38b2126
Create Date: 2025-09-19 18:25:22.880728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e2033a14a9'
down_revision: Union[str, Sequence[str], None] = 'a28fa38b2126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_name_key', 'company', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('company_name_key', 'company', ['name'])
    # ### end Alembic commands ###
