"""update col foriegn key in dept

Revision ID: 715ed238d46f
Revises: 36f4b90bba76
Create Date: 2025-11-18 19:55:17.825727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715ed238d46f'
down_revision: Union[str, Sequence[str], None] = '36f4b90bba76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('department', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'department', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'created_at')
    op.drop_column('department', 'company_id')
    # ### end Alembic commands ###
