"""Adding slug to jobs

Revision ID: 791dc5be28c9
Revises: a9df5bae2206
Create Date: 2025-09-20 11:26:42.960996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791dc5be28c9'
down_revision: Union[str, Sequence[str], None] = 'a9df5bae2206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'job', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='unique')
    op.drop_column('job', 'slug')
    # ### end Alembic commands ###
