"""update the payment table plus schemas

Revision ID: 8adaad45beeb
Revises: 26a2d695185c
Create Date: 2025-09-27 09:53:18.223762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adaad45beeb'
down_revision: Union[str, Sequence[str], None] = '26a2d695185c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'payment', ['stripe_payment_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
