"""apply adter payments

Revision ID: 8d30e29d4089
Revises: ee6f9df5301d
Create Date: 2025-09-27 17:54:12.322020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d30e29d4089'
down_revision: Union[str, Sequence[str], None] = 'ee6f9df5301d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'payment', ['stripe_payment_intent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
