"""add questionsform

Revision ID: 9498fdfc99a1
Revises: 70e2033a14a9
Create Date: 2025-09-19 19:57:48.120984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9498fdfc99a1'
down_revision: Union[str, Sequence[str], None] = '70e2033a14a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_form',
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_id')
    )
    op.create_index(op.f('ix_questions_form_form_id'), 'questions_form', ['form_id'], unique=False)
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['questions_form.form_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_question_question_id'), 'question', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_questions_form_form_id'), table_name='questions_form')
    op.drop_table('questions_form')
    # ### end Alembic commands ###
