"""new department table

Revision ID: 9528165a092b
Revises: 020aca631ea7
Create Date: 2025-11-15 19:34:56.446847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9528165a092b'
down_revision: Union[str, Sequence[str], None] = '020aca631ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_department_department_id'), 'department', ['department_id'], unique=False)
    op.add_column('job', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('experience', sa.Float(), nullable=True))
    op.add_column('job', sa.Column('skills_weight', sa.Float(), nullable=True))
    op.add_column('job', sa.Column('experience_weight', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'job', 'department', ['department_id'], ['department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_column('job', 'experience_weight')
    op.drop_column('job', 'skills_weight')
    op.drop_column('job', 'experience')
    op.drop_column('job', 'department_id')
    op.drop_index(op.f('ix_department_department_id'), table_name='department')
    op.drop_table('department')
    # ### end Alembic commands ###
