"""change the resume parse table 

Revision ID: 993a992e80b9
Revises: 4bd4b59369d8
Create Date: 2025-10-04 14:15:35.692925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993a992e80b9'
down_revision: Union[str, Sequence[str], None] = '4bd4b59369d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_parsing', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'resume_parsing', 'candidate', ['candidate_id'], ['candidate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_parsing', type_='foreignkey')
    op.drop_column('resume_parsing', 'candidate_id')
    # ### end Alembic commands ###
