"""add interviewed flag

Revision ID: 9c3acfa37c4a
Revises: 65019afbad81
Create Date: 2026-01-29 20:44:35.604067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3acfa37c4a'
down_revision: Union[str, Sequence[str], None] = '65019afbad81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('interviewed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'interviewed')
    # ### end Alembic commands ###
