"""Initial migration

Revision ID: a28fa38b2126
Revises: 8f76f623267c
Create Date: 2025-09-19 15:47:33.328191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28fa38b2126'
down_revision: Union[str, Sequence[str], None] = '8f76f623267c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('company_name_key'), 'company', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('company_name_key'), 'company', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
