"""add company and hrs

Revision ID: a3a0ca0de4b4
Revises: bac84f3a0c33
Create Date: 2025-09-17 19:24:40.961899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a0ca0de4b4'
down_revision: Union[str, Sequence[str], None] = 'bac84f3a0c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_tokens_hr_id_fkey'), 'auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'auth_tokens', 'hr_manager', ['hr_id'], ['id'])
    op.drop_constraint(op.f('company_email_key'), 'company', type_='unique')
    op.drop_column('company', 'password')
    op.drop_column('company', 'email')
    op.add_column('hr_manager', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_hr_manager_hr_id'), table_name='hr_manager')
    op.create_index(op.f('ix_hr_manager_id'), 'hr_manager', ['id'], unique=False)
    op.drop_column('hr_manager', 'hr_id')
    op.drop_constraint(op.f('job_hr_id_fkey'), 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'hr_manager', ['hr_id'], ['id'])
    op.drop_constraint(op.f('notification_hr_id_fkey'), 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'hr_manager', ['hr_id'], ['id'])
    op.drop_column('notification', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(op.f('notification_hr_id_fkey'), 'notification', 'hr_manager', ['hr_id'], ['hr_id'])
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key(op.f('job_hr_id_fkey'), 'job', 'hr_manager', ['hr_id'], ['hr_id'])
    op.add_column('hr_manager', sa.Column('hr_id', sa.INTEGER(), server_default=sa.text("nextval('hr_manager_hr_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_hr_manager_id'), table_name='hr_manager')
    op.create_index(op.f('ix_hr_manager_hr_id'), 'hr_manager', ['hr_id'], unique=False)
    op.drop_column('hr_manager', 'id')
    op.add_column('company', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('company', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('company_email_key'), 'company', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'auth_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('auth_tokens_hr_id_fkey'), 'auth_tokens', 'hr_manager', ['hr_id'], ['hr_id'])
    # ### end Alembic commands ###
