"""update can table col createdat

Revision ID: b30649d7a34e
Revises: fcdf195e9ac7
Create Date: 2025-11-19 21:30:42.837054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30649d7a34e'
down_revision: Union[str, Sequence[str], None] = 'fcdf195e9ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'created_at')
    # ### end Alembic commands ###
