"""add google tokens

Revision ID: c3d13ec90f43
Revises: 8d30e29d4089
Create Date: 2025-09-28 17:54:42.226830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d13ec90f43'
down_revision: Union[str, Sequence[str], None] = '8d30e29d4089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hr_id'], ['hr_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_token_id'), 'google_token', ['id'], unique=False)
    op.create_index(op.f('ix_google_token_user_id'), 'google_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_token_user_id'), table_name='google_token')
    op.drop_index(op.f('ix_google_token_id'), table_name='google_token')
    op.drop_table('google_token')
    # ### end Alembic commands ###
