"""candidate selection

Revision ID: c4b737b62abe
Revises: c616396b4224
Create Date: 2025-11-06 18:54:06.469583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b737b62abe'
down_revision: Union[str, Sequence[str], None] = 'c616396b4224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('selected_for_interview', sa.Boolean(), nullable=False))
    op.add_column('candidate', sa.Column('selected', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'selected')
    op.drop_column('candidate', 'selected_for_interview')
    # ### end Alembic commands ###
