"""fix interview-slot relationship

Revision ID: c616396b4224
Revises: 175d9a042627
Create Date: 2025-11-06 17:44:53.596738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c616396b4224'
down_revision: Union[str, Sequence[str], None] = '175d9a042627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('interview_slot_interview_id_fkey'), 'interview_slot', type_='foreignkey')
    op.drop_column('interview_slot', 'interview_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_slot', sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('interview_slot_interview_id_fkey'), 'interview_slot', 'interview', ['interview_id'], ['interview_id'])
    # ### end Alembic commands ###
