"""update col foriegn key in depart

Revision ID: ca970393d94b
Revises: 715ed238d46f
Create Date: 2025-11-18 19:55:54.608383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca970393d94b'
down_revision: Union[str, Sequence[str], None] = '715ed238d46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('department', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'department', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'created_at')
    op.drop_column('department', 'company_id')
    # ### end Alembic commands ###
