"""update job col applicants and selected

Revision ID: caa2eb582b9d
Revises: cbffdad24f97
Create Date: 2025-11-19 20:06:20.370155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa2eb582b9d'
down_revision: Union[str, Sequence[str], None] = 'cbffdad24f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('applicants', sa.Integer(), nullable=True))
    op.add_column('job', sa.Column('selected', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'selected')
    op.drop_column('job', 'applicants')
    # ### end Alembic commands ###
