"""update col comp id  depart

Revision ID: cbffdad24f97
Revises: ca970393d94b
Create Date: 2025-11-18 19:56:37.485902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbffdad24f97'
down_revision: Union[str, Sequence[str], None] = 'ca970393d94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('department', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'department', 'company', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'created_at')
    op.drop_column('department', 'company_id')
    # ### end Alembic commands ###
