"""add col in candidate table

Revision ID: cc90f65b0288
Revises: fb46b98a001b
Create Date: 2026-03-16 15:08:26.595810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc90f65b0288'
down_revision: Union[str, Sequence[str], None] = 'fb46b98a001b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('invited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'invited_at')
    # ### end Alembic commands ###
