"""update job type col in job

Revision ID: d0dd7782b8bc
Revises: 828ea24feaf7
Create Date: 2025-11-17 20:31:14.241872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0dd7782b8bc'
down_revision: Union[str, Sequence[str], None] = '828ea24feaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_type')
    # ### end Alembic commands ###
