"""add hr availability and interviews 

Revision ID: d53ab6d678d3
Revises: 24c2a44fda4f
Create Date: 2025-11-06 17:15:44.552700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53ab6d678d3'
down_revision: Union[str, Sequence[str], None] = '24c2a44fda4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hr_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Text(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hr_id'], ['hr_manager.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_availability_id'), 'hr_availability', ['id'], unique=False)
    op.add_column('interview', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.add_column('interview', sa.Column('job_id', sa.Integer(), nullable=False))
    op.add_column('interview', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('interview', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'interview', 'job', ['job_id'], ['job_id'])
    op.create_foreign_key(None, 'interview', 'candidate', ['candidate_id'], ['candidate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.alter_column('interview', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('interview', 'created_at')
    op.drop_column('interview', 'job_id')
    op.drop_column('interview', 'candidate_id')
    op.drop_index(op.f('ix_hr_availability_id'), table_name='hr_availability')
    op.drop_table('hr_availability')
    # ### end Alembic commands ###
