"""add candidate with answers

Revision ID: f0e4d7d380a6
Revises: 791dc5be28c9
Create Date: 2025-09-20 19:24:42.420472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e4d7d380a6'
down_revision: Union[str, Sequence[str], None] = '791dc5be28c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('job_id', sa.Integer(), nullable=False))
    op.add_column('candidate', sa.Column('resume_url', sa.String(), nullable=False))
    op.create_foreign_key(None, 'candidate', 'job', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'resume_url')
    op.drop_column('candidate', 'job_id')
    # ### end Alembic commands ###
