"""update db cascading issues

Revision ID: f94cc4f36c15
Revises: aaefc287bf5b
Create Date: 2025-12-14 18:10:09.447287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94cc4f36c15'
down_revision: Union[str, Sequence[str], None] = 'aaefc287bf5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('candidate_job_id_fkey'), 'candidate', type_='foreignkey')
    op.create_foreign_key(None, 'candidate', 'job', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_department_id_fkey'), 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'department', ['department_id'], ['department_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key(op.f('job_department_id_fkey'), 'job', 'department', ['department_id'], ['department_id'])
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_job_id_fkey'), 'candidate', 'job', ['job_id'], ['job_id'])
    # ### end Alembic commands ###
