"""add isactive col in document template

Revision ID: fb46b98a001b
Revises: c6d480f8917c
Create Date: 2026-02-28 20:47:04.004916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb46b98a001b'
down_revision: Union[str, Sequence[str], None] = 'c6d480f8917c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_template', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_template', 'is_active')
    # ### end Alembic commands ###
