"""update can table col ai_score

Revision ID: fcdf195e9ac7
Revises: caa2eb582b9d
Create Date: 2025-11-19 20:50:21.908140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcdf195e9ac7'
down_revision: Union[str, Sequence[str], None] = 'caa2eb582b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('ai_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'ai_score')
    # ### end Alembic commands ###
